basePath: /
definitions:
  dtos.GetPropertyDTO:
    description: GetPropertyDTO represents the details of a property along with identifier
      information.
    properties:
      availability_status:
        description: property's availability status
        example: available
        type: string
      id:
        description: Property ID
        example: 1
        type: integer
      lessor_id:
        description: Lessor ID
        example: 10
        type: integer
      location:
        description: property's location
        example: California
        type: string
      name:
        description: name of the property
        example: Sunset Villa
        type: string
      price:
        description: property's price
        example: 1.2000005e+06
        type: number
      size:
        description: property's size
        example: 3500 sqft
        type: string
    type: object
  dtos.LoginDTO:
    description: LoginDTO represents a request for user login.
    properties:
      email:
        description: user's email
        example: john.doe@example.com
        type: string
      password:
        description: user's password
        example: strongPassword123
        type: string
    type: object
  dtos.PropertyDTO:
    description: PropertyDTO represents a property.
    properties:
      location:
        description: property location
        example: California
        type: string
      name:
        description: name of the property
        example: Sunset Villa
        type: string
      price:
        description: property price
        example: 1.2000005e+06
        type: number
      size:
        description: property size
        example: 3500 sqft
        type: string
      status:
        description: availability status
        example: available
        type: string
    type: object
  dtos.RegisterDTO:
    description: RegisterDTO represents a request for user registration.
    properties:
      address:
        description: user's address
        example: 1234 Main St, Springfield
        type: string
      email:
        description: user's email
        example: john.doe@example.com
        type: string
      name:
        description: user's first name
        example: John
        type: string
      password:
        description: user's password
        example: strongPassword123
        type: string
      role:
        description: 'role: lessor, lessee'
        example: lessee
        type: string
    type: object
  utils.Response:
    properties:
      data: {}
      message:
        example: message
        type: string
      status_code:
        example: 888
        type: integer
    type: object
host: localhost:5000/api/v1
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: API documentation for LeaseEase.
  title: LeaseEase API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and set an authentication cookie.
      operationId: "2"
      parameters:
      - description: Login request payload
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginDTO'
      produces:
      - application/json
      responses:
        "201":
          description: User login successfully
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
        "400":
          description: Invalid request payload
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
        "500":
          description: Internal server error
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
      summary: Login an existing user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user account with the provided details.
      operationId: "1"
      parameters:
      - description: Register request payload
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/dtos.RegisterDTO'
      produces:
      - application/json
      responses:
        "201":
          description: 'User registered successfully"  example({"staus_code": 201,
            "message": "User registered successfully", "data": nil})'
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: Invalid request payload
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
        "500":
          description: Internal server error
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
      summary: Register a new user
      tags:
      - auth
  /properties:
    get:
      consumes:
      - application/json
      description: Retrieve list of all properties with pagination
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Properties retrieved successfully
          schema:
            items:
              allOf:
              - $ref: '#/definitions/utils.Response'
              - properties:
                  data:
                    items:
                      $ref: '#/definitions/dtos.GetPropertyDTO'
                    type: array
                type: object
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
      security:
      - cookieAuth: []
      summary: Get all properties
      tags:
      - Property
  /properties/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve property details by its ID
      parameters:
      - description: Property ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Property retrieved successfully
          schema:
            items:
              allOf:
              - $ref: '#/definitions/utils.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dtos.GetPropertyDTO'
                type: object
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
        "404":
          description: Not Found
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
      security:
      - cookieAuth: []
      summary: Get property by ID
      tags:
      - Property
  /properties/create:
    post:
      consumes:
      - application/json
      description: Create a new property
      parameters:
      - description: Property Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.PropertyDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Property created successfully
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
      security:
      - cookieAuth: []
      summary: Create a property
      tags:
      - Property
  /properties/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a property by ID
      parameters:
      - description: Property ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Property deleted successfully
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
      security:
      - cookieAuth: []
      summary: Delete a property
      tags:
      - Property
  /properties/update/{id}:
    put:
      consumes:
      - application/json
      description: Update existing property data
      parameters:
      - description: Property ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated property data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.PropertyDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Property updated successfully
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/utils.Response'
            type: array
      security:
      - cookieAuth: []
      summary: Update a property
      tags:
      - Property
swagger: "2.0"
