name: CI/CD for Golang Backend

on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.23

            - name: Install Dependencies
              run: go mod tidy

            # - name: Run Tests
            #   run: go test ./...

    build-and-push-docker:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker Image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/leaseease-backend:latest .
                  docker push ${{ secrets.DOCKER_USERNAME }}/leaseease-backend:latest

    deploy:
        needs: build-and-push-docker
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Render
              run: |
                  curl -X POST https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}/
